//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDN_Video_Uploader.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class AppSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static AppSettings defaultInstance = ((AppSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AppSettings())));
        
        public static AppSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FtpHostname {
            get {
                return ((string)(this["FtpHostname"]));
            }
            set {
                this["FtpHostname"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FtpUsername {
            get {
                return ((string)(this["FtpUsername"]));
            }
            set {
                this["FtpUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FtpPassword {
            get {
                return ((string)(this["FtpPassword"]));
            }
            set {
                this["FtpPassword"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>1080p | ffmpeg.exe -i {input} -c copy {output}-1080p.mp4</string>
  <string>720p | ffmpeg.exe -i {input} -vcodec libx264 -crf 27 -preset veryfast -c:a copy -s 1280x720 {output}</string>
  <string>480p | ffmpeg.exe -i {input} -vcodec libx264 -crf 27 -preset veryfast -c:a copy -s 854x480 {output}</string>
  <string>240p | ffmpeg.exe -i {input} -vcodec libx264 -crf 27 -preset veryfast -c:a copy -s 426x240 {output}</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection TranscodingProfiles {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["TranscodingProfiles"]));
            }
        }
    }
}
